[project]
name = "chess-engine-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.12"
dependencies = [
    "chess>=1.11.2",
    "flax>=0.7.2",
    "jax>=0.4.13",
    "zstandard>=0.24.0",
]
